-- =============================================================================
-- SCRIPT DE CRIAÇÃO DE ESTRUTURA - ORACLE DATABASE 11g
-- SISTEMA: QA EVIDENCE TRACKER
-- DATA: 2024
-- =============================================================================

-- 1. TABELA DE USUÁRIOS
-- Armazena credenciais e perfil de acesso
CREATE TABLE TB_USERS (
    ID_USER VARCHAR2(36) NOT NULL,
    ACRONYM VARCHAR2(3) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL, -- ADMIN, USER
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,    -- 1 = Ativo, 0 = Inativo
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_USERS PRIMARY KEY (ID_USER),
    CONSTRAINT UK_USERS_ACRONYM UNIQUE (ACRONYM),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('ADMIN', 'USER')),
    CONSTRAINT CK_USERS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

COMMENT ON TABLE TB_USERS IS 'Tabela de gerenciamento de usuários e acessos';

-- 2. TABELA DE CHAMADOS (TICKETS)
-- Cabeçalho das evidências
CREATE TABLE TB_TICKETS (
    ID_TICKET VARCHAR2(36) NOT NULL,
    EXTERNAL_TICKET_ID VARCHAR2(50),    -- ID Visual (ex: 58645)
    TITLE VARCHAR2(255) NOT NULL,
    SUMMARY VARCHAR2(255),
    PRIORITY VARCHAR2(20) DEFAULT 'Média',
    SPRINT VARCHAR2(50),
    REQUESTER VARCHAR2(100),
    ANALYST_ACRONYM VARCHAR2(3),        -- Analista executor
    CLIENT_SYSTEM VARCHAR2(100),
    ENVIRONMENT VARCHAR2(255),          -- Ambientes (Trunk V11, Protheus...)
    ENV_VERSION VARCHAR2(50),
    REQUEST_DATE DATE,
    EVIDENCE_DATE DATE,
    DESCRIPTION CLOB,                   -- Descrição longa
    SOLUTION CLOB,                      -- Solução aplicada
    CREATED_BY VARCHAR2(3) NOT NULL,    -- FK para TB_USERS.ACRONYM
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ARCHIVED_AT TIMESTAMP,              -- Data de salvamento no histórico
    
    CONSTRAINT PK_TICKETS PRIMARY KEY (ID_TICKET),
    CONSTRAINT FK_TICKETS_USER FOREIGN KEY (CREATED_BY) REFERENCES TB_USERS (ACRONYM)
);

COMMENT ON TABLE TB_TICKETS IS 'Histórico de chamados e cabeçalhos de evidência';

-- 3. TABELA DE EVIDÊNCIAS (CENÁRIOS E CASOS)
-- Detalhes dos testes executados dentro de um chamado
CREATE TABLE TB_EVIDENCES (
    ID_EVIDENCE VARCHAR2(36) NOT NULL,
    ID_TICKET VARCHAR2(36) NOT NULL,
    TITLE VARCHAR2(255),
    DESCRIPTION CLOB,
    IMAGE_URL CLOB,                     -- Evidência manual simples (Base64)
    STATUS VARCHAR2(20) NOT NULL,       -- PASS, FAIL, BLOCKED, PENDING, SKIPPED
    SEVERITY VARCHAR2(20),              -- LOW, MEDIUM, HIGH, CRITICAL
    TIMESTAMP NUMBER,                   -- Epoch timestamp da criação
    
    -- Dados Específicos do Caso de Teste (Wizard)
    CASE_ID_DISPLAY VARCHAR2(50),       -- Ex: QA-12345
    SCENARIO_NUMBER NUMBER,
    CASE_NUMBER NUMBER,
    SCREEN_NAME VARCHAR2(100),
    OBJECTIVE CLOB,
    PRE_REQUISITE CLOB,
    CONDITION_DESC CLOB,                -- Gherkin: Dado/Quando/E
    EXPECTED_RESULT CLOB,               -- Gherkin: Então
    FAILURE_REASON CLOB,                -- Motivo da falha
    
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_EVIDENCES PRIMARY KEY (ID_EVIDENCE),
    CONSTRAINT FK_EVIDENCES_TICKET FOREIGN KEY (ID_TICKET) 
        REFERENCES TB_TICKETS (ID_TICKET) ON DELETE CASCADE,
    CONSTRAINT CK_EVIDENCE_STATUS CHECK (STATUS IN ('PASS', 'FAIL', 'BLOCKED', 'SKIPPED', 'PENDING'))
);

COMMENT ON TABLE TB_EVIDENCES IS 'Armazena cenários de teste e evidências manuais';

-- 4. TABELA DE PASSOS DA EVIDÊNCIA (STEPS)
-- Passos detalhados de um caso de teste (Timeline)
CREATE TABLE TB_EVIDENCE_STEPS (
    ID_STEP NUMBER NOT NULL,            -- Auto Increment via Sequence
    ID_EVIDENCE VARCHAR2(36) NOT NULL,
    STEP_NUMBER NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    IMAGE_DATA CLOB,                    -- Print do passo (Base64)
    
    CONSTRAINT PK_EVIDENCE_STEPS PRIMARY KEY (ID_STEP),
    CONSTRAINT FK_STEPS_EVIDENCE FOREIGN KEY (ID_EVIDENCE) 
        REFERENCES TB_EVIDENCES (ID_EVIDENCE) ON DELETE CASCADE
);

-- Sequence e Trigger para Auto Incremento (Padrão Oracle 11g)
CREATE SEQUENCE SEQ_EVIDENCE_STEPS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_EVIDENCE_STEPS_ID
BEFORE INSERT ON TB_EVIDENCE_STEPS
FOR EACH ROW
BEGIN
    SELECT SEQ_EVIDENCE_STEPS.NEXTVAL INTO :NEW.ID_STEP FROM DUAL;
END;
/

-- 5. TABELA DE REGISTRO DE BUGS
-- Módulo independente de reporte de erros
CREATE TABLE TB_BUGS (
    ID_BUG VARCHAR2(36) NOT NULL,
    SUMMARY VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(50) DEFAULT 'Pendente',
    PRIORITY VARCHAR2(20) DEFAULT 'Média',
    SCREEN VARCHAR2(100),
    MODULE VARCHAR2(100),
    ENVIRONMENT VARCHAR2(255),
    BUG_DATE DATE,
    DEV_RESPONSIBLE VARCHAR2(100),
    ANALYST_NAME VARCHAR2(200),
    
    PRE_REQUISITES CLOB,
    SCENARIO_DESC CLOB,
    EXPECTED_RESULT CLOB,
    ERROR_DESCRIPTION CLOB,
    DEV_FEEDBACK CLOB,
    OBSERVATION CLOB,
    
    CREATED_BY VARCHAR2(3) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_BUGS PRIMARY KEY (ID_BUG),
    CONSTRAINT FK_BUGS_USER FOREIGN KEY (CREATED_BY) REFERENCES TB_USERS (ACRONYM)
);

COMMENT ON TABLE TB_BUGS IS 'Registro e controle de Bugs encontrados';

-- 6. TABELA DE ANEXOS DO BUG
-- Prints anexados ao reporte de bug
CREATE TABLE TB_BUG_ATTACHMENTS (
    ID_ATTACHMENT NUMBER NOT NULL,      -- Auto Increment via Sequence
    ID_BUG VARCHAR2(36) NOT NULL,
    IMAGE_DATA CLOB,                    -- Imagem Base64
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT PK_BUG_ATTACHMENTS PRIMARY KEY (ID_ATTACHMENT),
    CONSTRAINT FK_ATTACHMENTS_BUG FOREIGN KEY (ID_BUG) 
        REFERENCES TB_BUGS (ID_BUG) ON DELETE CASCADE
);

-- Sequence e Trigger para Auto Incremento
CREATE SEQUENCE SEQ_BUG_ATTACHMENTS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_BUG_ATTACHMENTS_ID
BEFORE INSERT ON TB_BUG_ATTACHMENTS
FOR EACH ROW
BEGIN
    SELECT SEQ_BUG_ATTACHMENTS.NEXTVAL INTO :NEW.ID_ATTACHMENT FROM DUAL;
END;
/

-- 7. ÍNDICES PARA PERFORMANCE
CREATE INDEX IDX_TICKETS_USER ON TB_TICKETS(CREATED_BY);
CREATE INDEX IDX_TICKETS_DATE ON TB_TICKETS(EVIDENCE_DATE);
CREATE INDEX IDX_TICKETS_EXT_ID ON TB_TICKETS(EXTERNAL_TICKET_ID);

CREATE INDEX IDX_EVIDENCES_TICKET ON TB_EVIDENCES(ID_TICKET);
CREATE INDEX IDX_EVIDENCES_STATUS ON TB_EVIDENCES(STATUS);

CREATE INDEX IDX_BUGS_USER ON TB_BUGS(CREATED_BY);
CREATE INDEX IDX_BUGS_STATUS ON TB_BUGS(STATUS);
CREATE INDEX IDX_STEPS_EVIDENCE ON TB_EVIDENCE_STEPS(ID_EVIDENCE);

-- FIM DO SCRIPT